# Generated by Django 2.2.4 on 2019-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='pagers',
        ),
        migrations.AddField(
            model_name='pager',
            name='channels',
            field=models.ManyToManyField(to='pager.Channel'),
        ),
    ]
