# Generated by Django 2.2.4 on 2019-08-24 18:33

from django.db import migrations, models
import pager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0003_gmailchannel_recipient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pager',
            name='secret',
        ),
        migrations.AlterField(
            model_name='pager',
            name='slug',
            field=models.CharField(default=pager.models.gen_secret, max_length=255, unique=True),
        ),
    ]
